language: c

branches:
  only:
    - master

install:
  - MINICONDA=Miniconda-latest-Linux-x86_64.sh
  - wget http://repo.continuum.io/miniconda/$MINICONDA
  - bash $MINICONDA -b
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda install --yes conda-build

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.3
    - CONDA_PY=3.4

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe
