language: c

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_05e80f56939b_key -iv $encrypted_05e80f56939b_iv -in .pypirc.enc -out ~/.pypirc -d

install:
  - MINICONDA=Miniconda-latest-Linux-x86_64.sh
  - wget http://repo.continuum.io/miniconda/$MINICONDA
  - bash $MINICONDA -b
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda install --yes conda-build
  - conda config --add channels r

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.3
    - CONDA_PY=3.4

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe

after_success:
    - '[ "${CONDA_PY}" = "2.7" ] &&
        conda install --yes ~/miniconda/conda-bld/*/pyhmc*.bz2 &&
        conda install --yes pip cython numpy sphinx numpydoc &&
        pip install sphinx_rtd_theme &&
        cd docs && make html && cd - &&
        python setup.py upload_docs --upload-dir docs/_build/html'
