package:
    name: pyhmc
    version: "0.1"

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - statsmodels
    - cython
    - numpy
  run:
    - python
    - setuptools
    - statsmodels
    - numpy
    - scipy

test:
  requires:
    - nose
    - gcc
    - statsmodels
    - rpy2
    - r-coda        # spectrum0, spectrum0.ar, effectiveSize
  imports:
    - pyhmc
  commands:
    - nosetests pyhmc.tests

about:
  home: https://github.com/rmcgibbo/pyhmc
  license: BSD
  summary: 'pyhmc: Hamiltonain Monte Carlo Sampling in Python'
