package:
    name: pyhmc
    version: !!str 0.1

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
  run:
    - python
    - setuptools
    - numpy
    - scipy

test:
  requires:
    - nose
    - statsmodels
    - rpy2
    - r-coda
    - r-batchmeans
  imports:
    - pyhmc
  commands:
    - nosetests pyhmc.tests

about:
  home: https://github.com/rmcgibbo/pyhmc
  license: BSD
  summary: 'pyhmc: Hamiltonain Monte Carlo Sampling in Python'
